service: router

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi: ANY /{any+}

plugins:
  - serverless-offline
